---
root: true
extends: eslint:recommended
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 8
rules:
  array-bracket-spacing: error
  array-callback-return: error
  arrow-spacing: error
  block-spacing:
  - error
  - always
  brace-style:
  - error
  - 1tbs
  - allowSingleLine: true
  comma-dangle:
  - error
  - always-multiline
  comma-spacing:
  - error
  - before: false
    after: true
  comma-style:
  - error
  - last
  computed-property-spacing:
  - error
  - never
  consistent-this:
  - error
  - that
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  global-require: error
  indent:
  - error
  - 2
  - SwitchCase: 1
  key-spacing:
  - error
  - mode: minimum
  keyword-spacing:
  - error
  - before: true
    after: true
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  - code: 115
    tabWidth: 4
    ignoreComments: false
  new-cap: error
  no-array-constructor: error
  no-console: 'off'
  no-duplicate-imports: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multiple-empty-lines: error
  no-sequences: error
  no-trailing-spaces: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unused-vars:
  - error
  - args: none
  no-use-before-define: error
  no-var: error
  no-whitespace-before-property: error
  no-with: error
  object-curly-spacing:
  - error
  - always
  padded-blocks:
  - error
  - never
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error
  quotes:
  - error
  - single
  semi-spacing: error
  semi:
  - error
  - always
  space-before-blocks:
  - error
  - always
  space-before-function-paren:
  - error
  - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  template-curly-spacing:
  - error
  - never
  unicode-bom:
  - error
  - never
