language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless
script:
  - eslint .
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: 
    - sls deploy --verbose
  on:
    branch: develop
