language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - npm install
jobs:
  include: # defaults to test stage
    - script: eslint . 
    - script: npm test
    - stage: deploy
      script: skip
      install: npm install -g serverless
      deploy:
        skip_cleanup: true
        provider: script
        on:
          branch: staging
        script: 
          - sls deploy --verbose
        # After_deploy not working. Could use for slack notifications though
    - stage: deploy # Tag daily Release
        before_deploy:
          # Set up git user name and tag this commit
          - git config --local user.name "DailyBot"
          - git config --local user.email "noreply@example.com"
          - git tag "$(date +'%Y%m%d%_H%M%S')-$(git log --format=%h -1)"
        install:
          - npm install -g serverless
        script:
          - sls package --package ./serverless_package
        deploy:
          on:
            branch: staging
          provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: ./serverless_package/travis-ci-test.zip
          skip_cleanup: true
