language: node_js
node_js:
  - "6.10"
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
jobs:
  include: # defaults to test stage
    - script: eslint . 
    - script: npm test
    - stage: deploy
      script:
        - sls package --package ./serverless_package
      install: npm install -g serverless
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "DailyBot"
        - git config --local user.email "noreply@example.com"
        - git tag "$(date +'%Y%m%d%_H%M%S')-$(git log --format=%h -1)"
      deploy:
        skip_cleanup: true
        provider: script
        on:
          branch: staging
        before_script:
          - docker pull hello-world
        script:
          - docker run hello-world
      deploy:
        script:
          - sls deploy --verbose --package ./serverless_package/travis-ci-test.zip
        on:
          branch: staging
          tags: true
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: ./serverless_package/travis-ci-test.zip
        skip_cleanup: true
