language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless
jobs:
  include:
    - script: eslint .
    - script: npm test
    - stage: deploy
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        on:
          branch: develop
        script: 
          - sls deploy --verbose
