name: jamestest

services:
  - name: webapp
    environment_slug: node-js
    github:
      repo: james-firth/cicd-test
      branch: do-app-monorepo-deploy
      deploy_on_push: true
    source_dir: web-app
    #  index_document: index.html # defaults to index so not needed$
    build_command: yarn build
