# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - restore_cache:
          keys:
            - james-test-12734891234
      - run: npm config set prefix '~/.npm-global'
      - run: ls ~/.npm-global
      - run: which sls
      - run: which serverless
      - run: sls deploy
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: mkdir ~/.npm-global
      - run: npm config set prefix '~/.npm-global'
      - run: sudo npm install -g serverless
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      - save_cache:
          paths:
            - ~/.npm-global/
          key: james-test-12734891234
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: npm test
workflows:
  version: 2
  simple-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

