# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # Pushes the deploy to AWS eventually
  deploy:
    docker:
      - image: circleci/node:6.10
    steps:
      - run: sls deploy

  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - run:  npm test

  # NPM install dependencies
  build:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
workflows:
  version: 2
  build-test-and-approve:
    jobs:
      - build
      - test:
        requires:
          - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
        requires:
          - hold


