# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: echo "Building stuff"
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: npm test
workflows:
  version: 2
  simple-workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires: # Does this seriously need to be double-indented?
            - hold
