# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  test:
    - run: npm test
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: echo "Building stuff"
workflows:
  version: 2
  simple-workflow:
    jobs:
      - build
      - test
