# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: ls /usr/local/bin/
      - run: export PATH=$PATH:/usr/local/bin
      - run: which sls
      - run: which serverless
      - run: sls deploy
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: sudo npm install -g serverless
      - run: npm install
      - run: which sls
      - run: which serverless
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: npm test
workflows:
  version: 2
  simple-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

