name: On PR

on:
  - pull_request
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Runs a single command using the runners shell
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  wip-checker:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create status
        run: |
          echo "github.sha: ${{ github.sha }} github: ${{github}}";
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${ GITHUB_SHA } \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "fail",
            "context": "jamestest/cicd-testing",
            "description": "My Description: ${{ github.event.workflow_run.conclusion }}",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }'
