name: Release testing
on:
  release:
    types: [released]

jobs:
  echo_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "URL ${{github.event.release.url}} || html url ${{github.event.release.html_url}} || EVENT ${{ github.event.release }}"
